### ISSUE TITLE
最近一批账号被封了，持续了四天了，还没解开

### ISSUE THREAD

**Issue by bestRunner** [liubo0621/wechat-spider#68]
![image](https://user-images.githubusercontent.com/36727232/210306276-cd341faf-3099-443e-8e83-3ee510d8e5f3.png)

**Comment by qq1065507891** [comment]
我这边也是这个问题，有什么解决方法吗？

**Comment by yongbeima** [comment]
已经7天了，还没解开。一周爬400次不到。

**Comment by bestRunner** [comment]
> 已经7天了，还没解开。一周爬400次不到。
应该都是12月底，被一次性封了

**Comment by bestRunner** [comment]
> 

都是12月底被封的吧

**Comment by bestRunner** [comment]
@yongbeima @qq1065507891 我感觉，只能注销掉账号，重新注册了

**Comment by qq1065507891** [comment]
@bestRunner 请问注销账号，重新注册，试过了吗？

**Comment by bestRunner** [comment]
> @bestRunner 请问注销账号，重新注册，试过了吗？
@qq1065507891 注销了，但是有15天的注销时间（期间可以撤销注销申请），十五天之后才能重新注册

**Comment by qq1065507891** [comment]
> 

多谢，我也注销尝试一下

**Comment by yongbeima** [comment]
@bestRunner 我2个手机号，之前备了几个微信号。我想找一下有什么低成本快速注册新微信号的方法。

**Comment by bestRunner** [comment]
@yongbeima 别想了，没有。可以买0月租的流量卡，只来注册账号，但是现在正规渠道都是要实名的

**Comment by yongbeima** [comment]
解封了。。。

**Comment by bestRunner** [comment]
> 解封了。。。

@yongbeima 是的，我的也解封了

**Comment by qq1065507891** [comment]
大家这几天有微信号被封吗？

**Comment by yongbeima** [comment]
我四个号全部被封了。。。。

**Comment by qq1065507891** [comment]
我也是，到现在还没解封------------------------------------------------------------------
***@***.***>
日　期：2023年03月03日 09:45:46
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [striver-ing/wechat-spider] 最近一批账号被封了，持续了四天了，还没解开 (Issue #68)

我四个号全部被封了。。。。

**Comment by bestRunner** [comment]
> 我四个号全部被封了。。。。

发你邮箱了

**Comment by St1pn** [comment]
各位大佬，被封时你们的爬取频率和爬取量都设置的是多少嘞
